version: 2.0
jobs:
    build:
        docker:
            - image: circleci/ruby:2.4.2-jessie-node
        steps:
            - checkout
            - run: echo "Hello World"

    deploy:
        master:
            branch: master
        steps:
            - run:
                name: Deploy Over SSH
                command: ssh ubuntu@ec2-13-209-41-76.ap-northeast-2.compute.amazonaws.com "./deployment.sh"

workflows:
    version: 2
    build-deploy:
        jobs:
            - build:
                filters:
                    branches:
                        only: master
            - deployment:
                requires:
                    - build
                filters:
                    branches:
                        only: master    
