name: Hello_world!

on: 
  push: # push의 경우에만 실행한다.
    branches: 
      - master # master branch에만 발생했을 경우 실행한다.

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout a Git repository at a particular version
      uses: actions/checkout@v2
      with:
        repository: s5kywa1k3r/circleCI-Study # default is ${{ github.repository }}
    
    - name: TSLint checks
      uses: mooyoul/tslint-actions@master
      with:
        # Github Token
        token: ${{ secrets.GITHUB_TOKEN }}
        # Path of TypeScript Project file
        #project: ??
        # Path of TSLint configuration
        config: Test/tslint.json
        # Glob pattern to match
        pattern: '*.ts'
    
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
      with:
        # Version Spec of the version to use.  Examples: 10.x, 10.15.1, >=10.15.0, lts
        #version: # optional, default is 10.x
        node-version: '12.14.0'
        # Optional registry to set up for auth. Will set the registry in a project level .npmrc and .yarnrc file, and set up auth to read in from env.NODE_AUTH_TOKEN
        # registry-url: # optional
        # Optional scope for authenticating against scoped registries
        # scope: # optional
    - run: npm install
    - run: npm i -D typescript jest @types/jest
    - run: npm i -D ts-jest
    - run: npm test

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            whoami
            ls -al
