name: Hello_world!

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        ls -al

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: TSLint ls -al
        run: |
          ls -al
      - name: TSLint checks
        uses: mooyoul/tslint-actions@master
        with:
          # Github Token
          token: ${{ secrets.GITHUB_TOKEN }}
          # Path of TypeScript Project file
          #project: /API
          # Path of TSLint configuration
          config: tslint2.json
          # Glob pattern to match
          pattern: '*.ts'
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            whoami
            ls -al
